# Generated by Django 5.2.10 on 2026-02-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan_type', models.CharField(choices=[('PL', 'Personal Loan'), ('BL', 'Business Loan')], max_length=10)),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cibil_score', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Process', 'Process'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('establish_year', models.IntegerField()),
                ('business_type', models.CharField(max_length=200)),
                ('is_itr', models.BooleanField(default=False)),
                ('residence_type', models.CharField(max_length=20)),
                ('office_space', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_name', models.CharField(max_length=200)),
                ('is_pf', models.BooleanField(default=False)),
                ('is_itr', models.BooleanField(default=False)),
                ('residence_type', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
