# Generated by Django 5.2.10 on 2026-02-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New Lead'), ('Login', 'Login Done'), ('Process', 'In Process'), ('Query', 'Query'), ('Rejected', 'Rejected'), ('Sanctioned', 'Sanctioned'), ('Disbursed', 'Disbursed'), ('Closed', 'Closed')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='customers.customer')),
            ],
        ),
    ]
