# Generated by Django 5.2.10 on 2026-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstatus',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='disbursement_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_disbursement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_query',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='is_sanction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='login_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='process_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='process_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='query_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='query_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='reject_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='reject_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='sanction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='sanction_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
