# Generated by Django 5.2.10 on 2026-02-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerstatus_disbursement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstatus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customerstatus',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='customerstatus',
            name='status',
        ),
        migrations.AlterField(
            model_name='customerstatus',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerstatus',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
